name : push events
on: 
  push:
    branches:
      - main
  schedule:
     - cron : '*/5 * * * *'
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: info
        run: |
           ls
